apiVersion: v1
kind: Service
metadata:
  labels:
    app: https-redirect
  name: https-redirect
spec:
  ports:
    - port: 80
      targetPort: bounce
      nodePort: 32550
  type: NodePort
  selector:
    app: https-redirect
