apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: https-redirect
  name: https-redirect
spec:
  replicas: 1
  selector:
    app: https-redirect
  template:
    metadata:
      labels:
        app: https-redirect
    spec:
      containers:
          - image: quay.io/coreos/nginx-https-redirect
            name: nginx-redirector
            ports:
            - containerPort: 80
              name: bounce
